version: '3'
services:
  web:
    build: .
    ports:
     - "8080:80"
    volumes:
      - ./app.conf:/etc/nginx/conf.d/app.conf
#      - ./index.php:/var/www/html/assets/index.php
      - ./index.php:/var/www/html/index.php